version: '3'

services:
  api:
    container_name: "printscript-api"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USERNAME: ${GITHUB_ACTOR}
        TOKEN: ${GITHUB_TOKEN}
    ports:
      - 8082:8080
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}