version: '3'

services:
  api:
    container_name: "printscript-api"
    build:
      context: .
      dockerfile: Dockerfile.multi
      args:
        GITHUB_USERNAME: ${USERNAME}
        GITHUB_TOKEN: ${TOKEN}
    ports:
      - 8082:8080
    environment:
      - USERNAME=${USERNAME}
      - TOKEN=${TOKEN}